variables:
  GIT_DEPTH: "3"
  CONAN_USER_HOME: "$CI_PROJECT_DIR"
  CONAN_REVISIONS_ENABLED: "1"
  CONAN_SYSREQUIRES_SUDO: "0"

stages:
  - export
  - deploy

export:
  stage: export
  image: python:3
  before_script:
    - pip3 install conan
    - conan user
    - conan config install https://github.com/hopobcn/conan-config.git
  script:
    - conan export .
    - conan inspect -a version .
  artifacts:
    paths:
    - .conan/data/conan-tools/*

deploy:
  stage: deploy
  image: python:3
  only:
    - tags
  dependencies:
    - export
  before_script:
    - pip3 install conan
    - conan user
    - conan config install https://github.com/hopobcn/conan-config.git
  script:
    - echo "upload to bintray here"

